name: flutter_ar_demo
description: "A Flutter AR demo using Camera and OpenCV."

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  camera_web: ^0.3.5
  image: ^3.0.1          # لمعالجة الصور الأساسية
  opencv_dart: ^1.3.3
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.11 # للوصول إلى مسارات الملفات (حفظ الصورة)
  flutter_webrtc: ^0.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
